replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: "v1.8.4"
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "4Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "1"

service:
  type: ClusterIP
  httpPort: 6333
  grpcPort: 6334

persistence:
  enabled: true
  size: 20Gi
  storageClass: gp2

nodeSelector:
  workload: general
