apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.uiPort }}
      targetPort: 16686
      protocol: TCP
      name: ui
    - port: {{ .Values.service.collectorGrpcPort }}
      targetPort: 14250
      protocol: TCP
      name: collector-grpc
    - port: {{ .Values.service.collectorHttpPort }}
      targetPort: 14268
      protocol: TCP
      name: collector-http
    - port: {{ .Values.service.otlpGrpcPort }}
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.otlpHttpPort }}
      targetPort: 4318
      protocol: TCP
      name: otlp-http
  selector:
    app: {{ .Release.Name }}
